name: Advent Of Code

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore src/src.csproj

    - name: Restore
      run: dotnet restore src/test.csproj

    - name: Build
      run: dotnet build --no-restore src.csproj

    - name: Test
      run: dotnet test --no-restore test.csproj
